#ifndef _POKEMON_H_
#define _POKEMON_H_

/*
  This file has been generated by IDA.
  It contains local type definitions from
  the type library 'moon'
*/

#include "qr.h"

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

typedef struct pgl_pokeparam_data
{
  int Key;
  char HyperTrainingFlags;
  char field_5;
  char field_6;
  char field_7;
  char PPUps[4];
  int IvFlags;
  int field_10;
  __int16 MonsNo;
  __int16 HoldItem;
  __int16 Moves[4];
  char field_20;
  char AbilityFlags;
  char Nature;
  char EncounterFlags;
  char EffortHp;
  char EffortAtk;
  char EffortDef;
  char EffortSpeed;
  char EffortSpAtk;
  char EffortSpDef;
  char field_2A;
  char Familiarity;
  char Pokeball;
  char Level;
  char CassetteVersion;
  char LangId;
} pokemon;

typedef struct {
} pm_team;

pokemon* initListWithQR(qr_dec_t* qr);
pokemon* initOneWithQR(u8* raw);

int isPM(pokemon* pm);

void printTeam(pokemon* pm);
void printPM(pokemon* pm);

#endif //_POKEMON_H_
